# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/11918/OneDrive/FPGA/project_3/project_3.srcs/sources_1/ip/pic/pic.xci
# IP: The module: 'pic' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/11918/OneDrive/FPGA/project_3/project_3.srcs/sources_1/ip/pic/pic_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pic'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/11918/OneDrive/FPGA/project_3/project_3.srcs/sources_1/ip/pic/pic.xci
# IP: The module: 'pic' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/11918/OneDrive/FPGA/project_3/project_3.srcs/sources_1/ip/pic/pic_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pic'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
