# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/11918/OneDrive/FPGA/project_3/project_3.cache/wt [current_project]
set_property parent.project_path C:/Users/11918/OneDrive/FPGA/project_3/project_3.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/11918/OneDrive/FPGA/project_3/project_3.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files C:/Users/11918/Desktop/coe/pic_1.coe
add_files C:/Users/11918/Desktop/coe/pic_2.coe
add_files C:/Users/11918/Desktop/coe/pic_3.coe
add_files C:/Users/11918/Desktop/coe/pic_4.coe
add_files C:/Users/11918/Desktop/coe/pic_5.coe
add_files C:/Users/11918/Desktop/coe/pic_6.coe
add_files C:/Users/11918/Desktop/coe/pic_7.coe
add_files C:/Users/11918/Desktop/coe/pic_8.coe
add_files C:/Users/11918/Desktop/coe/pic_9.coe
add_files C:/Users/11918/Desktop/coe/pic_10.coe
add_files C:/Users/11918/Desktop/coe/pic_11.coe
add_files C:/Users/11918/Desktop/coe/pic_12.coe
add_files C:/Users/11918/Desktop/coe/pic_13.coe
add_files C:/Users/11918/Desktop/coe/pic_14.coe
add_files C:/Users/11918/Desktop/coe/pic_15.coe
add_files C:/Users/11918/Desktop/coe/pic_16.coe
add_files C:/Users/11918/OneDrive/FPGA/project_3/zong.coe
read_verilog -library xil_defaultlib C:/Users/11918/OneDrive/FPGA/project_3/project_3.srcs/sources_1/new/vga.v
read_ip -quiet C:/Users/11918/OneDrive/FPGA/project_3/project_3.srcs/sources_1/ip/pic/pic.xci
set_property used_in_implementation false [get_files -all c:/Users/11918/OneDrive/FPGA/project_3/project_3.srcs/sources_1/ip/pic/pic_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/11918/OneDrive/FPGA/project_3/Nexys4DDR_Master.xdc
set_property used_in_implementation false [get_files C:/Users/11918/OneDrive/FPGA/project_3/Nexys4DDR_Master.xdc]


synth_design -top top -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb"
